books/urls.py
from django.urls import path
from .views import books_page, about,all_reviews,AddCommentView
from . import views


app_name = 'books'

urlpatterns = [
    path('books/', books_page, name='books_page'),
    path('about/<int:id>/', about, name='about_page'),  
    path('all_reviews/', all_reviews, name='all_reviews'), 
    path('add_comment/<int:id>/',AddCommentView.as_view(), name='add_comment'),  

    path('uzbek/', views.uzbek_books_view, name='uzbek_books'),
    path('english/', views.english_books_view, name='english_books'),
    path('russian/', views.russian_books_view, name='russian_books'),
    path('category/<int:category_id>/', views.category_books_view, name='category_books'),

]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from . import settings
from .views import base_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/',include('books.urls', namespace='books')),
    path('users/',include('users.urls')),
    path('', base_page, name='base'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileUpdateView, ProfileView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login_page/', LoginView.as_view(), name='login_page'),
    path('logout_page/', LogoutView.as_view(), name='logout_page'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('profile_view/', ProfileView.as_view(), name='profile_view'),   
]

users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

class User(AbstractUser):
    photo = models.ImageField(upload_to="user_photos/", null=True, blank=True)
    phone_number = models.CharField(max_length=13, unique=True, null=True, blank=True)

    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        related_name='custom_user_set',  # Specify unique related name
        related_query_name='group',
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        related_name='custom_user_set',  # Specify unique related name
        related_query_name='permission',
    )

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

users/forms.py
from .models import User
from django import forms

class RegisterForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super(RegisterForm,self).__init__(*args,**kwargs)
        self.fields['password_confirm']=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=['username','first_name','last_name','email','password','photo', 'phone_number']


    def clean_password_confirm(self):
        password=self.cleaned_data['password']
        password_confirm=self.cleaned_data['password_confirm']

        if password!=password_confirm:
            raise forms.ValidationError('Parolni tekshiring va bir xil kiriting')
        
        return password
    
    def clean_username(self):
        username=self.cleaned_data['username']

        if len(username)<4 or len(username)>30:
            raise forms.ValidationError('username uzunligi 5 dan katta 30 dan kichik bolishi kerakl')
        return username
    
    def clean_number(self):
        phone_number = self.cleaned_data['phone_number']
        if len(phone_number)!=13 or not phone_number.startswith('+998'):
             raise forms.ValidationError('Mobile raqam kiritishda xatolik')
 




class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username=self.cleaned_data['username']
        if not isinstance(username,str):
            raise forms.ValidationError('usernameni stringda kiriting')
        if len(username)<5 or len(username)>30:
            raise forms.ValidationError('username uzunligi 5 dan katta 30 dan kichik bolishi kerakl')
        return username
    
    def clean_password(self):
        password=self.cleaned_data['password']
        if not password.isdigit():
            raise forms.ValidationError('passwordni raqamda kiriting ')
        return password
    
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email','photo', 'phone_number']

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm, LoginForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'users/register.html', context={"form": form})
    
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            messages.success(request, "Siz muvaffaqiyatli registratsiya qildingiz ")
            return redirect('users/login_page')

        return render(request, 'users/register.html', context={"form": form})

class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'users/login_page.html', context={"form": form})
    
    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
             username = form.cleaned_data['username']
             password = form.cleaned_data['password']
             user = authenticate(username=username, password=password)
             if user is not None:
                 login(request, user)
                 messages.success(request, "Siz muvaffaqiyatli login qildingiz ")
                 return redirect('base')
        return render(request, 'users/login_page.html', context={"form": form})

class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, "Siz muvaffaqiyatli logout qildingiz ")
        return redirect('base')

class ProfileUpdateView(View):
    def get(self, request):
        form = ProfileUpdateForm(instance=request.user)
        return render(request, 'users/profile.html', context={"form": form})

    def post(self, request):
        form = ProfileUpdateForm(instance=request.user, data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()
            messages.info(request, "Siz muvaffaqiyatli yangilanish qildingiz ")
            return redirect('base')
        return render(request, 'users/profile.html', context={"form": form})

class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/profile_view.html')

users/templates/users/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
</head>
<body>
    {% include "navbar.html" %}
    


    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            padding: 20px;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .btn-primary {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: #0056b3;
        }

        .text-center {
            text-align: center;
        }

        .register-link {
            text-decoration: none;
            color: #007bff;
        }

        .register-link:hover {
            text-decoration: underline;
        }
    </style>
 
    <h1>Log in</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <p class="text-center">Do you have not an account? <a href="{% url 'users:register' %}" class="register-link">Sign up</a></p>

</body>
</html>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Page</title>
</head>
<body>
    {% include "navbar.html" %}
    
<title>Profile Page</title>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #F9F0DD;
        padding: 20px;
    }

    form {
        max-width: 400px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        margin-bottom: 20px;
    }

    input[type="text"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .btn-primary {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
</style>
<h1>Profile</h1>
<form action="" method="post" enctype = "multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
</form>

</body>
</html>

users/templates/users/profile_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block title%}

    {% endblock %}
</head>

<body class="px-5">
    {% include "navbar.html" %}
 

    <div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
        <div class="card p-4">
            <div class="image d-flex flex-column justify-content-center align-items-center">
                {% if user.photo %}
                <img src="{{ user.photo.url }}" style="border-radius: 50%;" height="150" width="150">
            {% else %}
           
                <img src="{% static 'default_image.jpg' %}" style="border-radius: 50%;" height="150" width="150">
            {% endif %}           
                <span class="name mt-3">{{user.username}}</span>
                <span class="idd">{{user.email}}</span>
                <div class="d-flex flex-row justify-content-center align-items-center gap-2">
                    <span class="idd1">{{user.phone_number}}</span>
                    <span><i class="fa fa-copy"></i></span>
                </div>
                <div class="d-flex mt-4">
                    <a href="{% url 'users:profile' %}" class="btn btn-dark"
                        style="font-size: 22px; padding: 10px 20px; border-radius: 10px;">Edit Profile</a>
                </div>

                <div class="px-2 rounded mt-4 date">
                    <span class="join">Joined {{user.date_joined|date:"M d, Y"}}</span>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var descriptions = document.querySelectorAll({{place.discription}});
            descriptions.forEach(function(description) {
                var text = description.innerText;
                if (text.length > 30) {
                    var newText = text.slice(0, 30) + '<br>' + text.slice(30);
                    description.innerHTML = newText;
                }
            });
        });
    </script>
</body>
</html>

users/templates/users/register.html
{% include "navbar.html" %}
<title>Register Page</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<!-- stil berish -->
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #F9F0DD;
        padding: 20px;
        
    }

    h2 {
        text-align: center;
        margin-bottom: 20px;
    }

    form {
        max-width: 500px;
      
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="password"],
    input[type="email"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .btn-primary {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
</style>
<h2>Register Page</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Register Page</button>
    <p class="text-center">Do you have an account?<a href="{% url 'users:login_page' %}" class="register-link">Sign up</a></p>
</form>