books/urls.py
from django.urls import path
from .views import books_page, about,all_reviews,AddCommentView
from . import views


app_name = 'books'

urlpatterns = [
    path('books/', books_page, name='books_page'),
    path('about/<int:id>/', about, name='about_page'),  
    path('all_reviews/', all_reviews, name='all_reviews'), 
    path('add_comment/<int:id>/',AddCommentView.as_view(), name='add_comment'),  

    path('uzbek/', views.uzbek_books_view, name='uzbek_books'),
    path('english/', views.english_books_view, name='english_books'),
    path('russian/', views.russian_books_view, name='russian_books'),
    path('category/<int:category_id>/', views.category_books_view, name='category_books'),

]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from . import settings
from .views import base_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/',include('books.urls', namespace='books')),
    path('users/',include('users.urls')),
    path('', base_page, name='base'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileUpdateView, ProfileView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login_page/', LoginView.as_view(), name='login_page'),
    path('logout_page/', LogoutView.as_view(), name='logout_page'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('profile_view/', ProfileView.as_view(), name='profile_view'),   
]

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
   
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="nav-link" href="#" style="margin-left:50px;">Books</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'base' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'books:books_page' %}">All books</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'books:all_reviews' %}">All reviews</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLanguage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Select language
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownLanguage">
            <a class="dropdown-item" href="{% url 'books:english_books' %}">English</a>
            <a class="dropdown-item" href="{% url 'books:russian_books' %}">Russian</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'books:uzbek_books' %}">Uzbek</a>
          </div>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-4" style="margin-right:50px" method="GET" action="{% url 'books:books_page' %}">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    
      <ul class="navbar-nav me-2 mb-4 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUser" role="button" data-toggle="dropdown" aria-expanded="false" style="font-size: larger;">
                {{ user.username }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownUser">
                <li><a class="dropdown-item" href="{% url 'users:profile_view' %}" style="font-size: larger;">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'users:logout_page' %}" style="font-size: larger;">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li><a class="nav-link" href="{% url 'users:login_page' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav> 
  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>